from ship import Ship

ship = Ship(id = 'cape_spear_trawler',
            numeric_id = '140',
            capacity_cargo_holds = 44,
            capacity_tanks = 0,
            replacement_id = '-none',
            fixed_run_cost_factor = 2.0,
            supertype = 'trawler',
            speed = 16.0,
            speed_factor_unladen = 1.15,
            title = 'Cape Spear [Trawler]',
            inland_capable = True,
            offsets = [[-14, -40], [-78, -21], [-68, -21], [-30, -21], [-14, -40], [-78, -24], [-68, -21], [-32, -21]],
            buy_menu_width = 51,
            capacity_freight = 44,
            loading_speed = '15',
            capacity_pax = 40,
            intro_date = 1870,
            buy_menu_bb_xy = [663, 21],
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}],
            graphics_template = 'default',
            str_type_info = 'TRAWLER',
            sea_capable = True,
            fuel_run_cost_factor = 1.0,
            buy_cost = 6,
            capacity_special = [84],
            vehicle_life = 40,
            capacity_mail = 66,
            custom_template = None,
            gross_tonnage = 84,
            default_cargo = 'FISH',
)
