from ship import Ship

ship = Ship(id = 'eddystone_tanker',
            numeric_id = '260', 
            capacity_cargo_holds = 0, 
            capacity_tanks = 330, 
            replacement_id = '-none', 
            fixed_run_cost_factor = 2.0, 
            supertype = 'tanker', 
            speed = 20.0, 
            speed_unladen = 22.0, 
            title = 'Eddystone [Tanker]', 
            inland_capable = True, 
            offsets = [[-14, -40], [-80, -24], [-66, -21], [-33, -25], [-14, -40], [-78, -26], [-66, -21], [-32, -23]], 
            buy_menu_width = 78, 
            capacity_freight = 330, 
            loading_speed = '40', 
            capacity_pax = 0, 
            intro_date = 1920, 
            buy_menu_bb_xy = [649, 21], 
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}], 
            graphics_template = 'tanker', 
            str_type_info = 'SMALL_TANKER_COASTAL_INLAND', 
            sea_capable = True, 
            fuel_run_cost_factor = 1.0, 
            buy_cost = 12, 
            capacity_special = [], 
            vehicle_life = 35, 
            capacity_mail = 0, 
            custom_template = None, 
            gross_tonnage = 350, 
            default_cargo = 'OIL_', 
)