from ship import Ship

ship = Ship(id = 'endeavour_utility_catamaran',
            numeric_id = '120',
            capacity_cargo_holds = 70,
            capacity_tanks = 0,
            capacity_mail = 70,
            capacity_special = [],
            replacement_id = '-none',
            fixed_run_cost_factor = 3.0,
            supertype = 'packet',
            speed = 45.0,
            speed_factor_unladen = 1.15,
            title = 'Endeavour [Rig Supply Fast Catamaran]',
            inland_capable = True,
            offsets = [[-14, -40], [-78, -21], [-68, -21], [-30, -21], [-14, -40], [-78, -24], [-68, -21], [-32, -21]],
            buy_menu_width = 49,
            capacity_freight = 70,
            loading_speed = '15',
            capacity_pax = 65,
            intro_date = 1998,
            buy_menu_bb_xy = [664, 21],
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}],
            graphics_template = 'default',
            str_type_info = 'RIG_SUPPLY_FAST_CATAMARAN',
            sea_capable = True,
            fuel_run_cost_factor = 1.0,
            buy_cost = 7,
            vehicle_life = 25,
            custom_template = None,
            gross_tonnage = 70,
            default_cargo = 'PASS',
)
