from ship import Ship

ship = Ship(id = 'fastnet_paddle_steamer',
            numeric_id = '40',
            capacity_cargo_holds = 250,
            capacity_tanks = 0,
            replacement_id = 'capo_sandalo_vehicle_ferry',
            fixed_run_cost_factor = 19.0,
            supertype = 'packet',
            speed = 23.0,
            speed_factor_unladen = 1.0,
            title = 'Fastnet [Paddle Steamer]',
            inland_capable = False,
            offsets = [[-14, -54], [-63, -24], [-50, -29], [-10, -28], [-14, -55], [-58, -27], [-50, -29], [-8, -24]],
            buy_menu_width = 138,
            capacity_freight = 250,
            loading_speed = '12',
            capacity_pax = 720,
            intro_date = 1918,
            buy_menu_bb_xy = [620, 26],
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}],
            graphics_template = 'default',
            str_type_info = 'PADDLE_STEAMER',
            sea_capable = True,
            fuel_run_cost_factor = 1.0,
            buy_cost = 79,
            capacity_special = [],
            vehicle_life = 40,
            capacity_mail = 320,
            custom_template = None,
            gross_tonnage = 800,
            default_cargo = 'PASS',
)
