from ship import Ship

ship = Ship(id = 'fish_island_trawler',
            numeric_id = '130', 
            capacity_cargo_holds = 20, 
            capacity_tanks = 0, 
            replacement_id = '-none', 
            fixed_run_cost_factor = 2.0, 
            supertype = 'trawler', 
            speed = 17.0, 
            speed_unladen = 19.549999999999997, 
            title = 'Fish Island [Trawler]', 
            inland_capable = True, 
            offsets = [[-14, -40], [-78, -21], [-68, -21], [-30, -21], [-14, -40], [-78, -24], [-68, -21], [-32, -21]], 
            buy_menu_width = 40, 
            capacity_freight = 20, 
            loading_speed = '15', 
            capacity_pax = 18, 
            intro_date = 1870, 
            buy_menu_bb_xy = [669, 21], 
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}], 
            graphics_template = 'default', 
            str_type_info = 'TRAWLER', 
            sea_capable = True, 
            fuel_run_cost_factor = 1.0, 
            buy_cost = 4, 
            capacity_special = [36], 
            vehicle_life = 40, 
            capacity_mail = 30, 
            custom_template = None, 
            gross_tonnage = 40, 
            default_cargo = 'FISH', 
)