from ship import Ship

ship = Ship(id = 'harbour_point_utility_vessel',
            numeric_id = '110', 
            capacity_cargo_holds = 15, 
            capacity_tanks = 0, 
            replacement_id = '-none', 
            fixed_run_cost_factor = 1.5, 
            supertype = 'trawler', 
            speed = 19.0, 
            speed_unladen = 21.849999999999998, 
            title = 'Harbour Point [Utility Vessel]', 
            inland_capable = True, 
            offsets = [[-14, -40], [-78, -21], [-68, -21], [-30, -21], [-14, -40], [-78, -24], [-68, -21], [-32, -21]], 
            buy_menu_width = 29, 
            capacity_freight = 15, 
            loading_speed = '15', 
            capacity_pax = 27, 
            intro_date = 1870, 
            buy_menu_bb_xy = [673, 23], 
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}], 
            graphics_template = 'default', 
            str_type_info = 'SMALL_GENERAL_PURPOSE_VESSEL', 
            sea_capable = True, 
            fuel_run_cost_factor = 1.0, 
            buy_cost = 2, 
            capacity_special = [], 
            vehicle_life = 40, 
            capacity_mail = 22, 
            custom_template = None, 
            gross_tonnage = 30, 
            default_cargo = 'PASS', 
)