from ship import Ship, PacketBoat

ship = PacketBoat(id = 'harbour_point_utility_vessel',
            numeric_id = 110,
            title = 'Harbour Point [Utility Vessel]',
            capacity_pax = 27,
            capacity_freight = 15,
            capacity_cargo_holds = 15,
            capacity_tanks = 0,
            capacity_mail = 22,
            capacity_special = [],
            replacement_id = '-none',
            buy_cost = 2,
            fixed_run_cost_factor = 1.5,
            fuel_run_cost_factor = 1.0,
            speed = 19.0,
            speed_factor_unladen = 1.15,
            inland_capable = True,
            sea_capable = True,
            offsets = [[-14, -40], [-78, -21], [-68, -21], [-30, -21], [-14, -40], [-78, -24], [-68, -21], [-32, -21]],
            buy_menu_width = 29,
            loading_speed = '15',
            intro_date = 1870,
            buy_menu_bb_xy = [673, 23],
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}],
            graphics_template = 'default',
            str_type_info = 'SMALL_GENERAL_PURPOSE_VESSEL',
            vehicle_life = 40,
            gross_tonnage = 30,
)
