from ship import Ship

ship = Ship(id = 'marstein_freighter',
            numeric_id = '200', 
            capacity_cargo_holds = 240, 
            capacity_tanks = 0, 
            replacement_id = '-none', 
            fixed_run_cost_factor = 3.5, 
            supertype = 'gcv', 
            speed = 26.0, 
            speed_unladen = 28.600000000000001, 
            title = 'Marstein [Freighter]', 
            inland_capable = False, 
            offsets = [[-14, -40], [-80, -24], [-66, -21], [-33, -25], [-14, -40], [-78, -26], [-66, -21], [-32, -23]], 
            buy_menu_width = 78, 
            capacity_freight = 240, 
            loading_speed = '20', 
            capacity_pax = 0, 
            intro_date = 2008, 
            buy_menu_bb_xy = [649, 21], 
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}], 
            graphics_template = 'standard_gcv', 
            str_type_info = 'COASTER', 
            sea_capable = True, 
            fuel_run_cost_factor = 1.0, 
            buy_cost = 22, 
            capacity_special = [], 
            vehicle_life = 40, 
            capacity_mail = 0, 
            custom_template = None, 
            gross_tonnage = 270, 
            default_cargo = 'COAL', 
)