from ship import Ship

ship = Ship(id = 'patos_island_vehicle_ferry',
            numeric_id = '50', 
            capacity_cargo_holds = 280, 
            capacity_tanks = 0, 
            replacement_id = '-none', 
            fixed_run_cost_factor = 5.0, 
            supertype = 'packet', 
            speed = 22.0, 
            speed_factor_unladen = 22.0, 
            title = 'Patos Island [Ferry]', 
            inland_capable = True, 
            offsets = [[-14, -54], [-61, -28], [-36, -29], [-10, -28], [-14, -54], [-55, -26], [-36, -29], [0, -24]], 
            buy_menu_width = 89, 
            capacity_freight = 280, 
            loading_speed = '35', 
            capacity_pax = 450, 
            intro_date = 1953, 
            buy_menu_bb_xy = [622, 28], 
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}], 
            graphics_template = 'default', 
            str_type_info = 'VEHICLE_FERRY', 
            sea_capable = True, 
            fuel_run_cost_factor = 1.0, 
            buy_cost = 27, 
            capacity_special = [], 
            vehicle_life = 60, 
            capacity_mail = 360, 
            custom_template = None, 
            gross_tonnage = 500, 
            default_cargo = 'PASS', 
)