from ship import Ship

ship = Ship(id = 'pine_island_log_tug',
            numeric_id = '250',
            capacity_pax = 0,
            capacity_freight = 0,
            capacity_cargo_holds = 0,
            capacity_tanks = 0,
            capacity_mail = 0,
            capacity_special = [80, 240, 400],
            replacement_id = '-none',
            buy_cost = 4,
            fixed_run_cost_factor = 2.0,
            fuel_run_cost_factor = 1.0,
            supertype = 'log_tug',
            speed = 12.0,
            speed_factor_unladen = 1.7,
            title = 'Pine Island [Log Tug]',
            inland_capable = False,
            offsets = [[0, 0]],
            buy_menu_width = 24,
            loading_speed = '20',
            intro_date = 1900,
            buy_menu_bb_xy = [620, 28],
            graphic_variations_by_date = [[[0, 9999]], {0: [0]}],
            graphics_template = 'default',
            str_type_info = 'LOG_TUG',
            sea_capable = True,
            vehicle_life = 25,
            custom_template = 'log_tug.pynml',
            gross_tonnage = 26,
            default_cargo = 'WOOD',
)
